### PR TITLE
Add posframe toolkit support

### PR DESCRIPTION
**Pull request by tumashu**
More info: https://github.com/tumashu/company-posframe/issues/1

### CODE REVIEW

**Comment by expez** [comment]
Hi, 
thanks for the PR but I have no interest in maintaining posframe support for company quickhelp.  I'm spending less and less time doing OSS work these days, and I don't want to take on any more commitments. 

I've already declined similar PRs where people wanted some alternative way of displaying popups, e.g. for use with terminal-only emacs.  

The code is open source so you're free to copy the quickhelp stuff into `company-posframe` itself and then just tell your users to uninstall company-quickhelp and use only company-posframe.

**Comment by cpitclaudel** [comment]
Is there any chance to have posframe offer an interface compatible with pos-tip? I imagine it might be fine to just introduce one variable in company-quickhelp offering users to put any custom function they wish; that function would default to pos-tip-show, but users could use pos-frame-show as well.

**Comment by dgutov** [comment]
Some way to display this using a child frame is really a must (postframe or otherwise).

Hoping for a new maintainer or a fork.

**Comment by tumashu** [comment]
I will add company-posframe-quickhelp to solve this problem in company-posframe

**Comment by tumashu** [comment]
https://github.com/tumashu/company-posframe/blob/master/company-posframe-quickhelp.el

**Comment by tumashu** [comment]
图片

**Comment by expez** [comment]
@cpitclaudel or @dgutov either of you want to maintain terminal support?

I'd be happy do add you as a maintainer @dgutov or even move this repo over to the `company-mode` org.

**Comment by dgutov** [comment]
> either of you want to maintain terminal support?

Myself - not really. The current proposed approach requires `popup.el` which does not have copyright assignment, and never will.

Lars, if you're winding down your OSS involvement entirely, please feel free to transfer this project to the `company-mode` org. I don't use it myself still, but I'll try to take care of maintenance.

By the way... was there a reason for this PR to keep `pos-tip` as an implementation option? A child frame should provide all the necessary capabilities. @tumashu

**Comment by tumashu** [comment]
pos-tip seem to code by one developer, is it easy to become a gnu elpa package?

**Comment by dgutov** [comment]
I'm pretty sure it has had multiple contributors over the years.

Anyway, doesn't posframe provide the same capabilities?

**Comment by tumashu** [comment]
posframe provide similar capabilities with pos-tip, some feature much better.

**Comment by cpitclaudel** [comment]
I don't care too much about terminal support @expez , but note that this PR isn't about that.  I still like the way I suggested above, where pos-frame would provide the same interface as pos-ip currently does and we'd swap out one for the other transparently.  This wouldn't add to the maintenance burden of this library.

**Comment by expez** [comment]
I'm not married to `pos-tip`, it was just the best library available at the time to show a doc popup in GUI emacs.

`pos-frame` support has been requested a few times now and it's usually in the context of adding terminal support. Maybe I've misunderstood.  If it's just strictly better than `pos-tip` (terminal or not) I'm all for switching over.  I don't have as much time for OSS work anymore, so I've just been trying to avoid adding features I'm not willing to maintain.

> Lars, if you're winding down your OSS involvement entirely, please feel free to transfer this project to the `company-mode` org.

I wouldn't say entirely, but with the limited time I spend on OSS I'm spread too thin atm.  I consider this library done (it's working perfectly for me), so if it's time for another round of development, moving it to the `company-mode` org would be most welcome.

So If I understand correctly, the next step is then:

1. Transfer ownership to you
2. You can then move it into the `company-mode` org
3. Update the melpa recipe

Is that about the gist of it?

**Comment by dgutov** [comment]
@cpitclaudel But is keeping pos-tip support at all valuable? Otherwise, this package could just switch to the new library, keeping the same overall level of complexity.

@expez I think you can only transfer a repository to an organization. So just steps 2 and 3.

**Comment by expez** [comment]
@dgutov 

image

I don't have the ability to create repos in the `company-mode` org, so unless you want to add me over there, it has to go through your user first.

**Comment by dgutov** [comment]
How about now? An invite (or two) should arrive now.

**Comment by dgutov** [comment]
Or transfer it to me, if that works. I just know that that wasn't allowed in GitHub at some point.

**Comment by expez** [comment]
@dgutov transferring to you.  Got an error saying I wasn't allowed to create public repos in the `company-mode` organization.

Thanks for adopting this project!

**Comment by dgutov** [comment]
@expez Thank you for your work on it!

@tumashu Do you want to open a PR that ports this project from pos-tip to posframe?

**Comment by expez** [comment]
@dgutov https://github.com/melpa/melpa/pull/6582 <- new recipe

**Comment by cpitclaudel** [comment]
> @cpitclaudel But is keeping pos-tip support at all valuable? Otherwise, this package could just switch to the new library, keeping the same overall level of complexity.

Not really, except to the extent that pos-tip is customizable and users might have customized its appearance.

**Comment by dgutov** [comment]
I'm not sure it would be so trivial to add the same calling convention to posframe as what pos-tip uses.

And I haven't looked at its codebase too close yet, but in principle I think we'd want to have all uses of pos-tip replaced with posframe (the child frames are sort of the recommended approach for this task).

**Comment by tumashu** [comment]
@expez @cpitclaudel Hello friends,  do you have signed FSF paper?  If no, do you interesting do this?

I want to move company-posframe into GNU elpa, but  company-posframe include some code from company-quickhelp to let quickhelp support posframe. so I need to know this info, 

https://github.com/tumashu/company-posframe/issues/48

**Comment by dgutov** [comment]
Looking at the internal list, @cpitclaudel signed it, but @expez did not (please correct me if you did).

**Pull request closed without merging**
